### PR TITLE
Add support for FeitCSI

### PR DESCRIPTION
**Pull request by KuskoSoft**
Added support for new CSI extraction tool [FeitCSI](https://feitcsi.kuskosoft.com/)

### CODE REVIEW

**Comment by Gi-z** [comment]
Woah, this is really cool! I'm currently away from home, or I'd be trying this out on a CM4 right now. 

Any chance you could provide some sample files so I can test this and get it merged asap?

**Comment by KuskoSoft** [comment]
I provide sample files in commit 984f673b3bec40b95c2fa1bd11a0d264c64f4891

**Comment by Gi-z** [comment]
Great! I'm getting ready to leave for a trip tomorrow so I'll see if I can get this merged and deployed today 👍

**Comment by Gi-z** [comment]
> I provide sample files in commit [984f673](https://github.com/Gi-z/CSIKit/commit/984f673b3bec40b95c2fa1bd11a0d264c64f4891)

Everything looks good, just got a question about timestamps.

In CSIKit I'm aiming for timestamps to identify the time at which a frame was captured. Ideally this would be absolute in epoch µs, but that's obviously not possible in all cases. Relative timestamps are fine too, and that's what we end up with in most cases. What's important is making sure all of the different formats parsed with CSIKit end up with the same (or very similar) internal representation. For instance, in PicoScenes I had to try a few different hardware configurations to establish proper mappings for the `muClock` readings to parseable seconds. 

Since you wrote FeitCSI, could you tell me what unit the `ftm_clock` field uses? I tried dividing by 1e6 and 1e9, however I thought it'd be best to confirm with you. The current code causes some pretty gnarly-looking results in the standard `csikit` output, so I just wanted to get that resolved before merging.

**Comment by Gi-z** [comment]
Wow, that's great! This is exactly what I was looking for, thank you! Should be able to merge this shortly.

**Comment by Gi-z** [comment]
@KuskoSoft That's v2.5 with FeitCSI support now live on PyPi. Thanks again for submitting the PR. FeitCSI is really cool and I'm so glad to see public open-source tools for AX-series support.

**Comment by KuskoSoft** [comment]
@Gi-z Thank you! Do you try it? If you have some tips how I can improve it, add some functionality don't hesitate to let me know.

**Pull request merged**
